### ISSUE TITLE
OSError: No command "c3d" found on host......

### ISSUE THREAD

**Issue by bigerHe** [mgoubran/HippMapp3r#1]
I already downloaded the  _Convert3D Medical Image Processing Tool_ . How can I have a command named c3d?  Thank you.

**Comment by entiri** [comment]
Hi @whui03 , have you tried installing keras-contrib? Running the following line prior to installation via pip should work.

`pip install git+https://www.github.com/keras-team/keras-contrib.git`

**Comment by whui03** [comment]
@entiri I have installed keras-contrib. But there still have that error.Thank you!

**Comment by mgoubran** [comment]
Hi @whui03 , are you sure you installed it within the environment?

**Comment by mgoubran** [comment]
Hi @bigerHe, sorry for the late reply. Are you sure it's in your bash path (bashrc or bash_profile)?

**Comment by whui03** [comment]
@mgoubran  Thank you! I found the error is related to the  "warp"  version. I've solved the problem.

**Comment by zavalian1** [comment]
I am also having trouble with c3d. I have Convert3D Medical Image Processing Tool downloaded and exported but I get the following error when trying to run hippmapper seg_hipp on a T1:

Standard error:
/bin/sh: /usr/local/bin/c3d: cannot execute binary file
Return code: 126

**Comment by entiri** [comment]
Hi @zavalian1, the error that comes up when running c3d may be a permissions error. If so, try running chmod on `/usr/local/bin/c3d`
